import type { Metadata } from "next";
import { Inter, Playfair_Display } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const interFont = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-inter",
});

const playfairDisplayFont = Playfair_Display({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-playfair-display",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${interFont.variable} ${playfairDisplayFont.variable}`}
      >
        <header>
          <div>
            <div className="site-logo">Universo em Foco</div>
            <p>Explore o incrível universo da ciência e tecnologia conosco.</p>
          </div>
          <nav>
            <Link href="/">Início</Link>
            {" | "}
            <Link href="/blog">Blog</Link>
            {" | "}
            <Link href="/loja">Loja</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
